#!/usr/bin/env python3

""" CommanLine API of this framework.

This script provides CommandLine API of the framework.

Its source is also an example of Python API.
"""

from class_entry import default_kernel_instance

if __name__ == '__main__':

    pipeline_entry = default_kernel_instance.byname('pipeline_entry')
    result, obj = pipeline_entry.call('execute', { 'pipeline': [
        {
            "start_from": {
                "start_from": {
                    "method": "byname",
                    "params": { "entry_name" : "cli_parser2"},
                },
                "method": "get_arglist",
                "label": "arglist_results",
            },
            "method": "parse",
            "params": { "arglist:": "arglist_results.arglist" },
            "label": "parser_results",
        },
        {
            "start_from": pipeline_entry,
            "method": "execute",
            "params": {
                "pipeline:": "parser_results.pipeline"
            }
        }
    ] } )

    print("clip result: {}".format(result[0]))

