#!/usr/bin/env python3

""" CommanLine API of this framework.

This script provides CommandLine API of the framework.
Please run it without parameters to get help on syntax.

Its source is also the simplest example of Python API.
"""

import sys
from class_entry import default_kernel_instance


if __name__ == '__main__':

    clip_entry  = default_kernel_instance.find_Entry('clip')

    kernel_params, pipe_calls = clip_entry.call('parse', {'arglist': sys.argv})

    ret_value = clip_entry.call('execute', { 'pipe_calls': pipe_calls })

    exit(ret_value)
